---
- name: Install Nginx
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx package on Debian
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name: "nginx"
        state: "present"
        update_cache: true

    - name: Install Nginx package on RedHat
      when: ansible_facts['os_family'] == "RedHat"
      dnf:
        name: "nginx"
        state: "present"
        update_cache: true

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Permanently enable http service
      when: ansible_facts['os_family'] == "RedHat"
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
